=== umendibe/ERRONKA5/WEB ORRIA/xsd/donazioak.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <xs:simpleType name="IFKmota">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z][0-9]{8}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="Izenak">
        <xs:restriction base="xs:string">
            <xs:maxLength value="150"/>
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="ErreferentziaMota">
        <xs:restriction base="xs:string">
            <xs:pattern value="(IR|EZ|EI)[0-9]{5}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:element name="donazioak">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="donazioa" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="enpresaEmaile">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="IFK" type="IFKmota" />
                                        <xs:element name="izena" type="Izenak" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="data" type="xs:date" />
                            <xs:element name="elikagaia" type="elikagaiaInfo" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="elikagaiaInfo">
        <xs:sequence>
            <xs:element name="ref" type="ErreferentziaMota" />
            <xs:element name="prodIzena" type="Izenak" />
            <xs:element name="kop" type="xs:nonNegativeInteger" />
            <xs:element name="manufakEnp" type="Izenak" />
            <xs:element name="iraun-data" type="xs:date" minOccurs="0" />
            <xs:element name="hoztu" type="xs:boolean" minOccurs="0" />
            <xs:element name="kontserba" type="xs:boolean" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="mota" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="iragankorra"/>
                    <xs:enumeration value="ez iragankorra"/>
                    <xs:enumeration value="erdi iragankorra"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
</xs:schema>

=== umendibe/ERRONKA5/WEB ORRIA/xml/donazioak.xml
<?xml version="1.0" encoding="utf-8"?>
<donazioak xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../xsd/donazioak.xsd">
    <donazioa>
        <enpresaEmaile>
            <IFK>A12345678</IFK>
            <izena>Esnekiak Donostia S.L.</izena>
        </enpresaEmaile>
        <data>2026-01-15</data>
        <elikagaia>
            <mota>iragankorra</mota>
            <ref>IR10025</ref>
            <prodIzena>Behi esne osoa</prodIzena>
            <kop>500</kop>
            <manufakEnp>Lactur S.A.</manufakEnp>
            <iraun-data>2026-03-01</iraun-data>
            <hoztu>BAI</hoztu>
        </elikagaia>
    </donazioa>

    <donazioa>
        <enpresaEmaile>
            <IFK>B87654321</IFK>
            <izena>Gure Lurreko Kontserbak</izena>
        </enpresaEmaile>
        <data>2026-03-26</data>
        <elikagaia>
            <mota>ez iragankorra</mota>
            <ref>EZ55443</ref>
            <prodIzena>Lekale egosiak (Babarrunak)</prodIzena>
            <kop>200</kop>
            <manufakEnp>Legunbreak Elkartea</manufakEnp>
            <kontserba>BAI</kontserba>
        </elikagaia>
    </donazioa>

    <donazioa>
        <enpresaEmaile>
            <IFK>G44556677</IFK>
            <izena>Fruitu eta Barazki Banatzailea</izena>
        </enpresaEmaile>
        <data>2026-03-10</data>
        <elikagaia>
            <mota>erdi iragankorra</mota>
            <ref>EI99887</ref>
            <prodIzena>Patata poltsak 5kg</prodIzena>
            <kop>40</kop>
            <manufakEnp>Arabako Patata Koop.</manufakEnp>
        </elikagaia>
    </donazioa>
</donazioak>
